// <auto-generated />
using AGM_API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AGM_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517210000_AddMachineModel")]
    partial class AddMachineModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
