// <auto-generated />
using System;
using AGM_API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AGM_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526175947_FieldDeleteCascade")]
    partial class FieldDeleteCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AGM_API.Models.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "Timestamp");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.Animal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnimalTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.AnimalType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.ToTable("AnimalType");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.Stall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StallTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FarmId");

                    b.HasIndex("StallTypeId");

                    b.ToTable("Stall");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.StallAnimal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnimalTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<long>("StallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("StallId");

                    b.ToTable("StallAnimal");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.StallEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AnimalTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<long>("StallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("StallId");

                    b.ToTable("StallEvent");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.StallType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StallType");
                });

            modelBuilder.Entity("AGM_API.Models.Crop.Crop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CropTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CropTypeId");

                    b.ToTable("Crop");
                });

            modelBuilder.Entity("AGM_API.Models.Crop.CropType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CropType");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.Farm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<long?>("FarmTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FarmTypeId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Farm");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmAnimal", b =>
                {
                    b.Property<long>("farm_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("animal_Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AnimalCount")
                        .HasColumnType("integer");

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.HasKey("farm_Id", "animal_Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("animal_Id");

                    b.ToTable("FarmAnimal");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmMember.FarmMember", b =>
                {
                    b.Property<long>("farm_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("person_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("role_Id")
                        .HasColumnType("bigint");

                    b.HasKey("farm_Id", "person_Id", "role_Id");

                    b.HasIndex("person_Id");

                    b.HasIndex("role_Id");

                    b.ToTable("FarmMember");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmMember.MemberRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MemberRole");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FarmType");
                });

            modelBuilder.Entity("AGM_API.Models.Field.Field", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AreaHa")
                        .HasColumnType("double precision");

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FarmId");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActionTypeId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Applicator")
                        .HasColumnType("text");

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FertilizerType")
                        .HasColumnType("integer");

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<double?>("NContent")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Pest")
                        .HasColumnType("text");

                    b.Property<string>("Product")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<long?>("SeasonId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<string>("Variety")
                        .HasColumnType("text");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FieldId");

                    b.HasIndex("SeasonId");

                    b.ToTable("FieldAction");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldActionMachine", b =>
                {
                    b.Property<long>("FieldActionId")
                        .HasColumnType("bigint");

                    b.Property<long>("MachineId")
                        .HasColumnType("bigint");

                    b.HasKey("FieldActionId", "MachineId");

                    b.HasIndex("MachineId");

                    b.ToTable("FieldActionMachine");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldActionPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FieldActionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldActionId");

                    b.ToTable("FieldActionPhoto");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldActionType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FieldActionType");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldKeyPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<Point>("Keypoint")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("FieldKeyPoint");
                });

            modelBuilder.Entity("AGM_API.Models.Machine.Machine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("text");

                    b.Property<long?>("MachineBrandId")
                        .HasColumnType("bigint");

                    b.Property<long>("MachineTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("YearOfManufacture")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FarmId");

                    b.HasIndex("MachineBrandId");

                    b.HasIndex("MachineTypeId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("AGM_API.Models.Machine.MachineBrand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MachineBrand");
                });

            modelBuilder.Entity("AGM_API.Models.Machine.MachineModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("MachineBrandId")
                        .HasColumnType("bigint");

                    b.Property<long>("MachineTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MachineBrandId");

                    b.HasIndex("MachineTypeId");

                    b.ToTable("MachineModel");
                });

            modelBuilder.Entity("AGM_API.Models.Machine.MachineService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MachineId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NextServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("Odometer")
                        .HasColumnType("integer");

                    b.Property<decimal?>("OperatingHours")
                        .HasColumnType("numeric");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineService");
                });

            modelBuilder.Entity("AGM_API.Models.Machine.MachineType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MachineType");
                });

            modelBuilder.Entity("AGM_API.Models.Person.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Person");
                });

            modelBuilder.Entity("AGM_API.Models.Season.Season", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FarmId");

                    b.ToTable("Season");
                });

            modelBuilder.Entity("AGM_API.Models.Season.SeasonField", b =>
                {
                    b.Property<long>("season_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("field_Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CropId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFertilized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHarvested")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("season_Id", "field_Id");

                    b.HasIndex("CropId");

                    b.HasIndex("field_Id");

                    b.ToTable("SeasonField");
                });

            modelBuilder.Entity("AGM_API.Models.Task.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedToId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<long?>("SeasonId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FarmId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("AGM_API.Models.Task.TaskField", b =>
                {
                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint");

                    b.HasKey("TaskId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("TaskField");
                });

            modelBuilder.Entity("AGM_API.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("UserCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasFilter("\"UserCode\" IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.Animal", b =>
                {
                    b.HasOne("AGM_API.Models.Animal.AnimalType", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnimalType");

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.AnimalType", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.Stall", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Farm.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Animal.StallType", "StallType")
                        .WithMany()
                        .HasForeignKey("StallTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Farm");

                    b.Navigation("StallType");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.StallAnimal", b =>
                {
                    b.HasOne("AGM_API.Models.Animal.AnimalType", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Animal.Stall", "Stall")
                        .WithMany("Animals")
                        .HasForeignKey("StallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalType");

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.StallEvent", b =>
                {
                    b.HasOne("AGM_API.Models.Animal.AnimalType", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId");

                    b.HasOne("AGM_API.Models.Animal.Stall", "Stall")
                        .WithMany()
                        .HasForeignKey("StallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalType");

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("AGM_API.Models.Crop.Crop", b =>
                {
                    b.HasOne("AGM_API.Models.Crop.CropType", "CropType")
                        .WithMany("Crops")
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropType");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.Farm", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Farm.FarmType", "FarmType")
                        .WithMany()
                        .HasForeignKey("FarmTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AGM_API.Models.Person.Person", "Owner")
                        .WithMany("OwnerOfFarms")
                        .HasForeignKey("OwnerId");

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("FarmType");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmAnimal", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Animal.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("animal_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Farm.Farm", "Farm")
                        .WithMany("farmAnimals")
                        .HasForeignKey("farm_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmMember.FarmMember", b =>
                {
                    b.HasOne("AGM_API.Models.Farm.Farm", "Farm")
                        .WithMany("farmMembers")
                        .HasForeignKey("farm_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Person.Person", "Person")
                        .WithMany("MemberOfFarms")
                        .HasForeignKey("person_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Farm.FarmMember.MemberRole", "Role")
                        .WithMany("memberRoles")
                        .HasForeignKey("role_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AGM_API.Models.Field.Field", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Farm.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldAction", b =>
                {
                    b.HasOne("AGM_API.Models.Field.FieldActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Field.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Season.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActionType");

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Field");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldActionMachine", b =>
                {
                    b.HasOne("AGM_API.Models.Field.FieldAction", "FieldAction")
                        .WithMany("Machines")
                        .HasForeignKey("FieldActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Machine.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldAction");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldActionPhoto", b =>
                {
                    b.HasOne("AGM_API.Models.Field.FieldAction", "FieldAction")
                        .WithMany()
                        .HasForeignKey("FieldActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldAction");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldKeyPoint", b =>
                {
                    b.HasOne("AGM_API.Models.Field.Field", "Field")
                        .WithMany("keyPoints")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AGM_API.Models.Machine.Machine", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Farm.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Machine.MachineBrand", "MachineBrand")
                        .WithMany()
                        .HasForeignKey("MachineBrandId");

                    b.HasOne("AGM_API.Models.Machine.MachineType", "MachineType")
                        .WithMany()
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Farm");

                    b.Navigation("MachineBrand");

                    b.Navigation("MachineType");
                });

            modelBuilder.Entity("AGM_API.Models.Machine.MachineModel", b =>
                {
                    b.HasOne("AGM_API.Models.Machine.MachineBrand", "MachineBrand")
                        .WithMany()
                        .HasForeignKey("MachineBrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AGM_API.Models.Machine.MachineType", "MachineType")
                        .WithMany()
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineBrand");

                    b.Navigation("MachineType");
                });

            modelBuilder.Entity("AGM_API.Models.Machine.MachineService", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Machine.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AGM_API.Models.Person.Person", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("AGM_API.Models.User", "User")
                        .WithOne("Person")
                        .HasForeignKey("AGM_API.Models.Person.Person", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AGM_API.Models.Season.Season", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Farm.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AGM_API.Models.Season.SeasonField", b =>
                {
                    b.HasOne("AGM_API.Models.Crop.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId");

                    b.HasOne("AGM_API.Models.Field.Field", "Field")
                        .WithMany()
                        .HasForeignKey("field_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Season.Season", "Season")
                        .WithMany("SeasonFields")
                        .HasForeignKey("season_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Field");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("AGM_API.Models.Task.Task", b =>
                {
                    b.HasOne("AGM_API.Models.Person.Person", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Farm.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Season.Season", "Season")
                        .WithMany("Tasks")
                        .HasForeignKey("SeasonId");

                    b.Navigation("AssignedTo");

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Farm");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("AGM_API.Models.Task.TaskField", b =>
                {
                    b.HasOne("AGM_API.Models.Field.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Task.Task", "Task")
                        .WithMany("Fields")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.Stall", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("AGM_API.Models.Crop.CropType", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.Farm", b =>
                {
                    b.Navigation("farmAnimals");

                    b.Navigation("farmMembers");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmMember.MemberRole", b =>
                {
                    b.Navigation("memberRoles");
                });

            modelBuilder.Entity("AGM_API.Models.Field.Field", b =>
                {
                    b.Navigation("keyPoints");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldAction", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("AGM_API.Models.Person.Person", b =>
                {
                    b.Navigation("MemberOfFarms");

                    b.Navigation("OwnerOfFarms");
                });

            modelBuilder.Entity("AGM_API.Models.Season.Season", b =>
                {
                    b.Navigation("SeasonFields");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AGM_API.Models.Task.Task", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("AGM_API.Models.User", b =>
                {
                    b.Navigation("Person")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
