// <auto-generated />
using System;
using AGM_API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AGM_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428194327_AddFieldActionType")]
    partial class AddFieldActionType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AGM_API.Models.Animal.Animal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnimalTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.AnimalType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.ToTable("AnimalType");
                });

            modelBuilder.Entity("AGM_API.Models.Crop.Crop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CropTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CropTypeId");

                    b.ToTable("Crop");
                });

            modelBuilder.Entity("AGM_API.Models.Crop.CropType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CropType");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.Farm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OwnerId");

                    b.ToTable("Farm");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmAnimal", b =>
                {
                    b.Property<long>("farm_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("animal_Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AnimalCount")
                        .HasColumnType("integer");

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.HasKey("farm_Id", "animal_Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("animal_Id");

                    b.ToTable("FarmAnimal");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmMember.FarmMember", b =>
                {
                    b.Property<long>("farm_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("person_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("role_Id")
                        .HasColumnType("bigint");

                    b.HasKey("farm_Id", "person_Id", "role_Id");

                    b.HasIndex("person_Id");

                    b.HasIndex("role_Id");

                    b.ToTable("FarmMember");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmMember.MemberRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MemberRole");
                });

            modelBuilder.Entity("AGM_API.Models.Field.Field", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AreaHa")
                        .HasColumnType("double precision");

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FarmId");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActionTypeId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision");

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FieldId");

                    b.ToTable("FieldAction");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldActionType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FieldActionType");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldKeyPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<Geometry>("Keypoint")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("FieldKeyPoint");
                });

            modelBuilder.Entity("AGM_API.Models.Person.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Person");
                });

            modelBuilder.Entity("AGM_API.Models.Season.Season", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FarmId");

                    b.ToTable("Season");
                });

            modelBuilder.Entity("AGM_API.Models.Season.SeasonField", b =>
                {
                    b.Property<long>("season_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("field_Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("CropId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFertilized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHarvested")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("season_Id", "field_Id");

                    b.HasIndex("CropId");

                    b.HasIndex("field_Id");

                    b.ToTable("SeasonField");
                });

            modelBuilder.Entity("AGM_API.Models.Task.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedToId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChangeById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<long?>("SeasonId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("ChangeById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FieldId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("AGM_API.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.Animal", b =>
                {
                    b.HasOne("AGM_API.Models.Animal.AnimalType", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnimalType");

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("AGM_API.Models.Animal.AnimalType", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("AGM_API.Models.Crop.Crop", b =>
                {
                    b.HasOne("AGM_API.Models.Crop.CropType", "CropType")
                        .WithMany("Crops")
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropType");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.Farm", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Person.Person", "Owner")
                        .WithMany("OwnerOfFarms")
                        .HasForeignKey("OwnerId");

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmAnimal", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Animal.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("animal_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Farm.Farm", "Farm")
                        .WithMany("farmAnimals")
                        .HasForeignKey("farm_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmMember.FarmMember", b =>
                {
                    b.HasOne("AGM_API.Models.Farm.Farm", "Farm")
                        .WithMany("farmMembers")
                        .HasForeignKey("farm_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Person.Person", "Person")
                        .WithMany("MemberOfFarms")
                        .HasForeignKey("person_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Farm.FarmMember.MemberRole", "Role")
                        .WithMany("memberRoles")
                        .HasForeignKey("role_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AGM_API.Models.Field.Field", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Farm.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldAction", b =>
                {
                    b.HasOne("AGM_API.Models.Field.FieldActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Field.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionType");

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AGM_API.Models.Field.FieldKeyPoint", b =>
                {
                    b.HasOne("AGM_API.Models.Field.Field", "Field")
                        .WithMany("keyPoints")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AGM_API.Models.Person.Person", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("AGM_API.Models.User", "User")
                        .WithOne("Person")
                        .HasForeignKey("AGM_API.Models.Person.Person", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AGM_API.Models.Season.Season", b =>
                {
                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Farm.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AGM_API.Models.Season.SeasonField", b =>
                {
                    b.HasOne("AGM_API.Models.Crop.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId");

                    b.HasOne("AGM_API.Models.Field.Field", "Field")
                        .WithMany()
                        .HasForeignKey("field_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AGM_API.Models.Season.Season", "Season")
                        .WithMany("SeasonFields")
                        .HasForeignKey("season_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Field");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("AGM_API.Models.Task.Task", b =>
                {
                    b.HasOne("AGM_API.Models.Person.Person", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("AGM_API.Models.User", "ChangeBy")
                        .WithMany()
                        .HasForeignKey("ChangeById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AGM_API.Models.Field.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId");

                    b.HasOne("AGM_API.Models.Season.Season", "Season")
                        .WithMany("Tasks")
                        .HasForeignKey("SeasonId");

                    b.Navigation("AssignedTo");

                    b.Navigation("ChangeBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Field");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("AGM_API.Models.Crop.CropType", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.Farm", b =>
                {
                    b.Navigation("farmAnimals");

                    b.Navigation("farmMembers");
                });

            modelBuilder.Entity("AGM_API.Models.Farm.FarmMember.MemberRole", b =>
                {
                    b.Navigation("memberRoles");
                });

            modelBuilder.Entity("AGM_API.Models.Field.Field", b =>
                {
                    b.Navigation("keyPoints");
                });

            modelBuilder.Entity("AGM_API.Models.Person.Person", b =>
                {
                    b.Navigation("MemberOfFarms");

                    b.Navigation("OwnerOfFarms");
                });

            modelBuilder.Entity("AGM_API.Models.Season.Season", b =>
                {
                    b.Navigation("SeasonFields");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AGM_API.Models.User", b =>
                {
                    b.Navigation("Person")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
